version: "3.8"
services:
  backend:
    image: backend_image
    container_name: backend
    build: "./backend"
    volumes:
      - ./:/app/backend
    command: python3 backend/manage.py runserver 0.0.0.0:30001
    networks:
      - django-nginx
    ports:
      - "30001:30001"
  frontend:
    image: frontend_image
    container_name: frontend
    build: "./frontend"
    volumes:
      - ./:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "8080:8080"
    command: npm --prefix frontend run serve
    depends_on:
      - backend
    restart: always
    networks:
      - django-nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
    networks:
      - django-nginx
  db:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'ecommerce'
      MYSQL_PASSWORD: '1181080029'
      MYSQL_ROOT_PASSWORD: '1181080029'
    ports:
      - "5107:3306"
    networks:
      - backend

volumes:
  django-static:

networks:
  django-nginx:
    driver: bridge
  backend:
    driver: bridge
    name: backend
